### ISSUE TITLE
SEO issue app.

### ISSUE THREAD

**Issue by a3code** [uniformdev/uniform-component-starter-kit#7]
There is some sort of issue with the page description at the header,
main/src/pages/_app.tsx
       ` <meta property="og:description" content={pageMetaDescription?.value as string} />`
should be replaced to 
`<meta name="description" content={pageMetaDescription?.value as string} />`

from SEO point of view it should be normal descriptions, now it is duplication for property="og:description" and even the lighthouse seo tool mentions it

**Comment by alexshyba** [comment]
This should be fixed in the latest.
